swagger: '2.0'
info:
  version: '1.0'
  title: Reference
  description: |
    The Reference API allows you to easily access a list of supported Countries, States, TimeZones and Currencies.
host: reference.azure.net
basePath: /v1/
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /Countries:
    get:
      summary: Getting All Countries
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Country'
  /TimeZones:
    get:
      summary: Getting All Time Zones
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/TimeZone'
  /Currencies:
    get:
      summary: Getting All Currencies
      description: Currency resources are returned in ascending alphabetical order by Code.
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Currency'
definitions:
  Country:
    type: object
    example:
      Id: 1
      Code: CA
      Name: Canada
      Version: 1
      States:
        - Name: Alberta
          Code: AB
    properties:
      Id:
        description: Identifier
        type: integer
        format: int32
      Code:
        description: Country Code. Uses the ISO 3166-1 alpha-2 standard
        type: string
      Name:
        description: Country name
        type: string
      Version:
        description: Latest version number
        type: integer
        format: int32
      States:
        description: States/Provinces
        type: array
        items:
          $ref: '#/definitions/State'
  State:
    type: object
    example:
      Name: Alberta
      Code: AB
      Id: 0
      CountryCode: ''
    properties:
      Name:
        description: Country name
        type: string
      Code:
        description: State/Province Code. Based off the ISO 3166-2 standard
        type: string
      Id:
        description: Reserved for future use
        type: integer
        format: int32
      CountryCode:
        description: Reserved for future use
        type: string
  TimeZone:
    type: object
    example:
      Id: Alaskan Standard Time
      Name: '(UTC-09:00) Alaska'
      SupportsDaylightSavingTime: true
    properties:
      Id:
        description: Identifier
        type: string
      Name:
        description: Name
        type: string
      SupportsDaylightSavingTime:
        description: A flag to indicate if this TimeZone observes Daylight Savings Time
        type: boolean
  Currency:
    description: |
      To represent a Currency symbol in unicode, use the format <code>&#(Code);</code>, for USD this would be <code>&#36;</code> which is displayed as &#36;    
    type: object
    example:
      Id: 106
      Name: United States Dollar
      Code: USD
      Symbol:
        - 36
      Version: 1
    properties:
      Id:
        description: Identifier
        type: integer
        format: int32
      Name:
        description: Currency Name
        type: string
      Code:
        description: Identifier for the Currency
        type: string
      Symbol:
        description: Unicode decimal value for symbols associated with this currency
        type: array
        items:
          type: integer
      Version:
        description: Latest version number
        type: integer
        format: int32
      LanguageNameMap:
        description: Reserved for future use
        type: string
